// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CambioPasswordTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void cambioPassword() {
    driver.Navigate().GoToUrl("http://localhost:57825/WebForm1.aspx");
    driver.FindElement(By.CssSelector(".auto-style3:nth-child(4)")).Click();
    driver.FindElement(By.Id("tbxUsuario")).Click();
    driver.FindElement(By.Id("tbxUsuario")).SendKeys("prueba1@ubu.es");
    driver.FindElement(By.Id("tbxPassword")).Click();
    driver.FindElement(By.Id("tbxPassword")).SendKeys("prueba1");
    driver.FindElement(By.Id("tbxPassword")).SendKeys(Keys.Enter);
    driver.FindElement(By.Id("lbCambiarPassword")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(4) > .auto-style36")).Click();
    driver.FindElement(By.Id("tbActual")).Click();
    driver.FindElement(By.Id("tbActual")).SendKeys("prueba2");
    driver.FindElement(By.Id("tbNueva")).Click();
    driver.FindElement(By.Id("tbNueva")).SendKeys("paco");
    driver.FindElement(By.CssSelector("tr:nth-child(8) > .auto-style37")).Click();
    driver.FindElement(By.Id("tbConfirmar")).Click();
    driver.FindElement(By.Id("tbConfirmar")).SendKeys("paco");
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(10) > .auto-style37"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.Id("btnAceptar"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector("tr:nth-child(10) > .auto-style37")).Click();
    driver.FindElement(By.Id("btnAceptar")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".auto-style61"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).ClickAndHold().Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".auto-style61"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector(".auto-style61"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Release().Perform();
    }
    driver.FindElement(By.CssSelector(".auto-style61")).Click();
  }
}
