// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InicioTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void inicio() {
    driver.Navigate().GoToUrl("http://localhost:57825/InicioSesion.aspx");
    driver.FindElement(By.Id("tbxUsuario")).Click();
    driver.FindElement(By.Id("tbxUsuario")).SendKeys("prueba1@ubu.es");
    driver.FindElement(By.Id("tbxPassword")).Click();
    driver.FindElement(By.Id("tbxPassword")).SendKeys("prueba1");
    driver.FindElement(By.Id("btnAceptar")).Click();
    driver.FindElement(By.Id("btnRaiz")).Click();
    driver.FindElement(By.Id("btnRaiz")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(6) > .auto-style143")).Text, Is.EqualTo(" "));
    driver.FindElement(By.Id("btnRaiz")).Click();
    driver.FindElement(By.Id("btnNombre")).Click();
    driver.FindElement(By.Id("tbNombre")).Click();
    driver.FindElement(By.Id("btnCNombre")).Click();
    driver.FindElement(By.Id("tbNombre")).Click();
    driver.FindElement(By.Id("tbNombre")).SendKeys("Prueba Inicio");
    driver.FindElement(By.Id("btnCNombre")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".auto-style123")).Text, Is.EqualTo("Información del usuario"));
    driver.FindElement(By.Id("btnPais")).Click();
    driver.FindElement(By.Id("tbPais")).Click();
    driver.FindElement(By.Id("tbPais")).SendKeys("Guatemala");
    driver.FindElement(By.Id("btnCPais")).Click();
    Assert.That(driver.FindElement(By.CssSelector("html")).Text, Is.EqualTo("UBUWarehouse       prueba1@ubu.es  \\\\n    Cerrar Sesión Cambiar Contraseña\\\\n              Posee un total de 3 elementos.      \\\\nInformación del usuario\\\\n        Nombre: Prueba Inicio  \\\\n              Pais: Guatemala\\\\n        Telefono: 607384274\\\\n           "));
    driver.FindElement(By.Id("btnTelefono")).Click();
    driver.FindElement(By.Id("tbTelefono")).Click();
    driver.FindElement(By.Id("tbTelefono")).SendKeys("paco");
    driver.FindElement(By.Id("btnCTelefono")).Click();
    Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(11) > .auto-style100")).Text, Is.EqualTo("El teléfono solo puede tener números o el + del prefijo"));
    driver.FindElement(By.CssSelector("tr:nth-child(10)")).Click();
    driver.FindElement(By.Id("tbTelefono")).SendKeys("644876234");
    driver.FindElement(By.Id("btnCTelefono")).Click();
    Assert.That(driver.FindElement(By.CssSelector("html")).Text, Is.EqualTo("UBUWarehouse       prueba1@ubu.es  \\\\n    Cerrar Sesión Cambiar Contraseña\\\\n              Posee un total de 3 elementos.      \\\\nInformación del usuario\\\\n        Nombre: Prueba Inicio  \\\\n              Pais: Guatemala\\\\n        Telefono: 644876234\\\\n           "));
    driver.FindElement(By.Id("btnTelefono")).Click();
    driver.FindElement(By.Id("tbTelefono")).Click();
    driver.FindElement(By.Id("tbTelefono")).SendKeys("+34643546324");
    driver.FindElement(By.Id("btnCTelefono")).Click();
    Assert.That(driver.FindElement(By.CssSelector("html")).Text, Is.EqualTo("UBUWarehouse       prueba1@ubu.es  \\\\n    Cerrar Sesión Cambiar Contraseña\\\\n              Posee un total de 3 elementos.      \\\\nInformación del usuario\\\\n        Nombre: Prueba Inicio  \\\\n              Pais: Guatemala\\\\n        Telefono: +34643546324\\\\n           "));
    driver.FindElement(By.Id("btnTelefono")).Click();
    driver.FindElement(By.Id("lbCambiarPassword")).Click();
    driver.FindElement(By.Id("lbInicio")).Click();
    driver.FindElement(By.Id("lbCerrarSesion")).Click();
    Assert.That(driver.FindElement(By.CssSelector("html")).Text, Is.EqualTo("Inicio de sesión\\\\n    Usuario  \\\\nContraseña\\\\n                         "));
  }
}
